//Povray v3 code generated by Open Babel
//Author: Steffen Reith <streit@streit.cc>
//Update (2010): Noel O'Boyle and Steven Wathen
//Date: Tue Dec 09 00:44:00 Central Europe Standard Time 2025

//Set some global parameters for display options
#declare BAS = true;
#declare TRANS = false;

#include "colors.inc"

// create a regular point light source
light_source {
  <4.21354,2.59253,-7.94604>
  color rgb <1,1,1>    // light's color
}

// set a color of the background (sky)
background { color rgb <0.95 0.95 0.95> }

// perspective (default) camera
camera {
  location  <2.21354,-0.407469,-9.94604>
  look_at   <2.21354,-0.407469,0.0539629>
  right     x*image_width/image_height
}

//Include header for povray
#include "babel_povray3.inc"

//Use PovRay3.6
#version 3.6;

//Print name of molecule while rendering
#render "\b\b \n\n"

//Coodinates of atoms 1 - 13
#declare mol_0_pos_1 = <0.93283,0.0155286,-0.0724361>;
#declare mol_0_pos_2 = <2.45283,0.0155286,-0.0724361>;
#declare mol_0_pos_3 = <2.9595,-1.17725,0.721898>;
#declare mol_0_pos_4 = <3.69015,-2.05156,0.158946>;
#declare mol_0_pos_5 = <2.61646,-1.31468,2.09297>;
#declare mol_0_pos_6 = <2.94282,-0.0729858,-1.45554>;
#declare mol_0_pos_7 = <0.576167,0.0799575,0.934311>;
#declare mol_0_pos_8 = <0.576162,-0.888553,-0.520012>;
#declare mol_0_pos_9 = <0.576161,0.85518,-0.631607>;
#declare mol_0_pos_10 = <2.8095,0.919609,0.375141>;
#declare mol_0_pos_11 = <2.07776,-0.670074,2.50802>;
#declare mol_0_pos_12 = <2.60282,-0.934821,-1.8822>;
#declare mol_0_pos_13 = <3.96282,-0.0729883,-1.45554>;

//Povray-description of atoms 1 - 13
#declare mol_0_atom1 = object {
	  Atom_C
	  translate mol_0_pos_1
	 }
#declare mol_0_atom2 = object {
	  Atom_C
	  translate mol_0_pos_2
	 }
#declare mol_0_atom3 = object {
	  Atom_C
	  translate mol_0_pos_3
	 }
#declare mol_0_atom4 = object {
	  Atom_O
	  translate mol_0_pos_4
	 }
#declare mol_0_atom5 = object {
	  Atom_O
	  translate mol_0_pos_5
	 }
#declare mol_0_atom6 = object {
	  Atom_N
	  translate mol_0_pos_6
	 }
#declare mol_0_atom7 = object {
	  Atom_H
	  translate mol_0_pos_7
	 }
#declare mol_0_atom8 = object {
	  Atom_H
	  translate mol_0_pos_8
	 }
#declare mol_0_atom9 = object {
	  Atom_H
	  translate mol_0_pos_9
	 }
#declare mol_0_atom10 = object {
	  Atom_H
	  translate mol_0_pos_10
	 }
#declare mol_0_atom11 = object {
	  Atom_H
	  translate mol_0_pos_11
	 }
#declare mol_0_atom12 = object {
	  Atom_H
	  translate mol_0_pos_12
	 }
#declare mol_0_atom13 = object {
	  Atom_H
	  translate mol_0_pos_13
	 }

//Povray-description of bonds 1 - 12
#if (BAS)
#declare mol_0_bond0 = object {
	  bond_1
	  scale <1.52,1.0000,1.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond1 = object {
	  bond_1
	  scale <1.52,1.0000,1.0000>
	  rotate <0.0000,0.0000,-51.695>
	  rotate <0.0000,-57.4681,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond2 = object {
	  bond_2
	  scale <1.2709,1.0000,1.0000>
	  rotate <0.0000,0.0000,-43.4675>
	  rotate <0.0000,37.6133,0.0000>
	  translate mol_0_pos_3
	 }
#declare mol_0_bond3 = object {
	  bond_1
	  scale <1.42,1.0000,1.0000>
	  rotate <0.0000,0.0000,-5.55374>
	  rotate <0.0000,-104.047,0.0000>
	  translate mol_0_pos_3
	 }
#declare mol_0_bond4 = object {
	  bond_1
	  scale <1.47,1.0000,1.0000>
	  rotate <0.0000,0.0000,-3.45209>
	  rotate <0.0000,70.4922,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond5 = object {
	  bond_1
	  scale <1.07,1.0000,1.0000>
	  rotate <0.0000,0.0000,3.45209>
	  rotate <0.0000,-109.508,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond6 = object {
	  bond_1
	  scale <1.07,1.0000,1.0000>
	  rotate <0.0000,0.0000,-57.6651>
	  rotate <0.0000,128.551,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond7 = object {
	  bond_1
	  scale <1.07,1.0000,1.0000>
	  rotate <0.0000,0.0000,51.6949>
	  rotate <0.0000,122.532,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond8 = object {
	  bond_1
	  scale <1.07,1.0000,1.0000>
	  rotate <0.0000,0.0000,57.665>
	  rotate <0.0000,-51.4491,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond9 = object {
	  bond_1
	  scale <0.937,1.0000,1.0000>
	  rotate <0.0000,0.0000,43.4675>
	  rotate <0.0000,-142.387,0.0000>
	  translate mol_0_pos_5
	 }
#declare mol_0_bond10 = object {
	  bond_1
	  scale <1.02,1.0000,1.0000>
	  rotate <0.0000,0.0000,-57.6651>
	  rotate <0.0000,128.551,0.0000>
	  translate mol_0_pos_6
	 }
#declare mol_0_bond11 = object {
	  bond_1
	  scale <1.02,1.0000,1.0000>
	  rotate <0.0000,0.0000,-0.000144737>
	  translate mol_0_pos_6
	 }
#end //(BAS-Bonds)

#if (CST)
#declare mol_0_bond0 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.76,1.0000,1.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.76,1.0000,1.0000>
	    rotate <0.0000,0.0000,180>
	    translate mol_0_pos_2
	   }
	  }
	 }

#declare mol_0_bond1 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.76,1.0000,1.0000>
	    rotate <0.0000,0.0000,-51.695>
	    rotate <0.0000,-57.4681,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_C2}
	    scale <0.76,1.0000,1.0000>
	    rotate <0.0000,0.0000,128.305>
	    rotate <0.0000,-57.4681,0.0000>
	    translate mol_0_pos_3
	   }
	  }
	 }

#declare mol_0_bond2 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_C2}
	    scale <0.63545,1.0000,1.0000>
	    rotate <0.0000,0.0000,-43.4675>
	    rotate <0.0000,37.6133,0.0000>
	    translate mol_0_pos_3
	   }
	   object {
	    bond_2
	    pigment{color Color_O2}
	    scale <0.63545,1.0000,1.0000>
	    rotate <0.0000,0.0000,136.532>
	    rotate <0.0000,37.6133,0.0000>
	    translate mol_0_pos_4
	   }
	  }
	 }

#declare mol_0_bond3 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C2}
	    scale <0.71,1.0000,1.0000>
	    rotate <0.0000,0.0000,-5.55374>
	    rotate <0.0000,-104.047,0.0000>
	    translate mol_0_pos_3
	   }
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.71,1.0000,1.0000>
	    rotate <0.0000,0.0000,174.446>
	    rotate <0.0000,-104.047,0.0000>
	    translate mol_0_pos_5
	   }
	  }
	 }

#declare mol_0_bond4 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.735,1.0000,1.0000>
	    rotate <0.0000,0.0000,-3.45209>
	    rotate <0.0000,70.4922,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_N3}
	    scale <0.735,1.0000,1.0000>
	    rotate <0.0000,0.0000,176.548>
	    rotate <0.0000,70.4922,0.0000>
	    translate mol_0_pos_6
	   }
	  }
	 }

#declare mol_0_bond5 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.535,1.0000,1.0000>
	    rotate <0.0000,0.0000,3.45209>
	    rotate <0.0000,-109.508,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.535,1.0000,1.0000>
	    rotate <0.0000,0.0000,183.452>
	    rotate <0.0000,-109.508,0.0000>
	    translate mol_0_pos_7
	   }
	  }
	 }

#declare mol_0_bond6 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.535,1.0000,1.0000>
	    rotate <0.0000,0.0000,-57.6651>
	    rotate <0.0000,128.551,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.535,1.0000,1.0000>
	    rotate <0.0000,0.0000,122.335>
	    rotate <0.0000,128.551,0.0000>
	    translate mol_0_pos_8
	   }
	  }
	 }

#declare mol_0_bond7 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.535,1.0000,1.0000>
	    rotate <0.0000,0.0000,51.6949>
	    rotate <0.0000,122.532,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.535,1.0000,1.0000>
	    rotate <0.0000,0.0000,231.695>
	    rotate <0.0000,122.532,0.0000>
	    translate mol_0_pos_9
	   }
	  }
	 }

#declare mol_0_bond8 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.535,1.0000,1.0000>
	    rotate <0.0000,0.0000,57.665>
	    rotate <0.0000,-51.4491,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.535,1.0000,1.0000>
	    rotate <0.0000,0.0000,237.665>
	    rotate <0.0000,-51.4491,0.0000>
	    translate mol_0_pos_10
	   }
	  }
	 }

#declare mol_0_bond9 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.4685,1.0000,1.0000>
	    rotate <0.0000,0.0000,43.4675>
	    rotate <0.0000,-142.387,0.0000>
	    translate mol_0_pos_5
	   }
	   object {
	    bond_1
	    pigment{color Color_HO}
	    scale <0.4685,1.0000,1.0000>
	    rotate <0.0000,0.0000,223.468>
	    rotate <0.0000,-142.387,0.0000>
	    translate mol_0_pos_11
	   }
	  }
	 }

#declare mol_0_bond10 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_N3}
	    scale <0.51,1.0000,1.0000>
	    rotate <0.0000,0.0000,-57.6651>
	    rotate <0.0000,128.551,0.0000>
	    translate mol_0_pos_6
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.51,1.0000,1.0000>
	    rotate <0.0000,0.0000,122.335>
	    rotate <0.0000,128.551,0.0000>
	    translate mol_0_pos_12
	   }
	  }
	 }

#declare mol_0_bond11 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_N3}
	    scale <0.51,1.0000,1.0000>
	    rotate <0.0000,0.0000,-0.000144737>
	    translate mol_0_pos_6
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.51,1.0000,1.0000>
	    rotate <0.0000,0.0000,180>
	    translate mol_0_pos_13
	   }
	  }
	 }

#end // (CST-Bonds)


//All atoms of molecule mol_0
#ifdef (TRANS)
#declare mol_0_atoms = merge {
#else
#declare mol_0_atoms = union {
#end //(End of TRANS)
	  object{mol_0_atom1}
	  object{mol_0_atom2}
	  object{mol_0_atom3}
	  object{mol_0_atom4}
	  object{mol_0_atom5}
	  object{mol_0_atom6}
	  object{mol_0_atom7}
	  object{mol_0_atom8}
	  object{mol_0_atom9}
	  object{mol_0_atom10}
	  object{mol_0_atom11}
	  object{mol_0_atom12}
	  object{mol_0_atom13}
	 }

//Bonds only needed for ball and sticks or capped sticks models
#if (BAS | CST)
#declare mol_0_bonds = union {
	  object{mol_0_bond0}
	  object{mol_0_bond1}
	  object{mol_0_bond2}
	  object{mol_0_bond3}
	  object{mol_0_bond4}
	  object{mol_0_bond5}
	  object{mol_0_bond6}
	  object{mol_0_bond7}
	  object{mol_0_bond8}
	  object{mol_0_bond9}
	  object{mol_0_bond10}
	  object{mol_0_bond11}
	 }
#end


//Definition of molecule mol_0
#if (SPF)
#declare mol_0 = object{
	  mol_0_atoms
#else
#declare mol_0 = union {
	  object{mol_0_atoms}
#if (BAS | CST)//(Not really needed at moment!)
#if (TRANS)
	  difference {
	   object{mol_0_bonds}
	   object{mol_0_atoms}
	  }
#else
	  object{mol_0_bonds}
#end //(End of TRANS)
#end //(End of (BAS|CST))
#end //(End of SPF)
//	  bounded_by {
//	   box {
//	    <-3,-5.05156,-4.8822>
//	    <6.96282,3.91961,5.50802>
	 }

//Center of molecule mol_0 (bounding box)
#declare mol_0_center = <-1.98141,0.565974,-0.312911>;

mol_0
