//Povray v3 code generated by Open Babel
//Author: Steffen Reith <streit@streit.cc>
//Update (2010): Noel O'Boyle and Steven Wathen
//Date: Sun Jan 04 22:38:46 Central Europe Standard Time 2026

//Set some global parameters for display options
#declare BAS = true;
#declare TRANS = false;

#include "colors.inc"

// create a regular point light source
light_source {
  <4.26118,2.55833,-8.30652>
  color rgb <1,1,1>    // light's color
}

// set a color of the background (sky)
background { color rgb <0.95 0.95 0.95> }

// perspective (default) camera
camera {
  location  <2.26118,-0.441674,-10.3065>
  look_at   <2.26118,-0.441674,-0.306524>
  right     x*image_width/image_height
}

//Include header for povray
#include "babel_povray3.inc"

//Use PovRay3.6
#version 3.6;

//Print name of molecule while rendering
#render "\b\b \n\n"

//Coodinates of atoms 1 - 13
#declare mol_0_pos_1 = <0.967958,-0.0904183,-0.0865056>;
#declare mol_0_pos_2 = <2.49056,-0.11701,-0.0727701>;
#declare mol_0_pos_3 = <3.02194,-1.49094,-0.518933>;
#declare mol_0_pos_4 = <3.68662,-1.67616,-1.53017>;
#declare mol_0_pos_5 = <2.71659,-2.49741,0.332554>;
#declare mol_0_pos_6 = <2.99675,0.944587,-0.967508>;
#declare mol_0_pos_7 = <0.554454,-0.809498,0.628447>;
#declare mol_0_pos_8 = <0.571097,-0.349663,-1.07474>;
#declare mol_0_pos_9 = <0.587719,0.900071,0.186839>;
#declare mol_0_pos_10 = <2.87091,0.0832549,0.934601>;
#declare mol_0_pos_11 = <2.21289,-2.21913,1.1205>;
#declare mol_0_pos_12 = <2.70177,0.72173,-1.92271>;
#declare mol_0_pos_13 = <4.01605,0.858816,-1.01442>;

//Povray-description of atoms 1 - 13
#declare mol_0_atom1 = object {
	  Atom_C
	  translate mol_0_pos_1
	 }
#declare mol_0_atom2 = object {
	  Atom_C
	  translate mol_0_pos_2
	 }
#declare mol_0_atom3 = object {
	  Atom_C
	  translate mol_0_pos_3
	 }
#declare mol_0_atom4 = object {
	  Atom_O
	  translate mol_0_pos_4
	 }
#declare mol_0_atom5 = object {
	  Atom_O
	  translate mol_0_pos_5
	 }
#declare mol_0_atom6 = object {
	  Atom_N
	  translate mol_0_pos_6
	 }
#declare mol_0_atom7 = object {
	  Atom_H
	  translate mol_0_pos_7
	 }
#declare mol_0_atom8 = object {
	  Atom_H
	  translate mol_0_pos_8
	 }
#declare mol_0_atom9 = object {
	  Atom_H
	  translate mol_0_pos_9
	 }
#declare mol_0_atom10 = object {
	  Atom_H
	  translate mol_0_pos_10
	 }
#declare mol_0_atom11 = object {
	  Atom_H
	  translate mol_0_pos_11
	 }
#declare mol_0_atom12 = object {
	  Atom_H
	  translate mol_0_pos_12
	 }
#declare mol_0_atom13 = object {
	  Atom_H
	  translate mol_0_pos_13
	 }

//Povray-description of bonds 1 - 12
#if (BAS)
#declare mol_0_bond0 = object {
	  bond_1
	  scale <1.52289,1.0000,1.0000>
	  rotate <0.0000,0.0000,-1.00052>
	  rotate <0.0000,-0.516857,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond1 = object {
	  bond_1
	  scale <1.53919,1.0000,1.0000>
	  rotate <0.0000,0.0000,-63.2056>
	  rotate <0.0000,40.0177,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond2 = object {
	  bond_2
	  scale <1.22421,1.0000,1.0000>
	  rotate <0.0000,0.0000,-8.70205>
	  rotate <0.0000,56.6834,0.0000>
	  translate mol_0_pos_3
	 }
#declare mol_0_bond3 = object {
	  bond_1
	  scale <1.35324,1.0000,1.0000>
	  rotate <0.0000,0.0000,-48.052>
	  rotate <0.0000,-109.728,0.0000>
	  translate mol_0_pos_3
	 }
#declare mol_0_bond4 = object {
	  bond_1
	  scale <1.47776,1.0000,1.0000>
	  rotate <0.0000,0.0000,45.9211>
	  rotate <0.0000,60.5012,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond5 = object {
	  bond_1
	  scale <1.09509,1.0000,1.0000>
	  rotate <0.0000,0.0000,-41.0442>
	  rotate <0.0000,-120.044,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond6 = object {
	  bond_1
	  scale <1.09604,1.0000,1.0000>
	  rotate <0.0000,0.0000,-13.6817>
	  rotate <0.0000,111.88,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond7 = object {
	  bond_1
	  scale <1.09561,1.0000,1.0000>
	  rotate <0.0000,0.0000,64.6957>
	  rotate <0.0000,-144.289,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond8 = object {
	  bond_1
	  scale <1.09525,1.0000,1.0000>
	  rotate <0.0000,0.0000,10.5358>
	  rotate <0.0000,-69.3152,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond9 = object {
	  bond_1
	  scale <0.975711,1.0000,1.0000>
	  rotate <0.0000,0.0000,16.5717>
	  rotate <0.0000,-122.589,0.0000>
	  translate mol_0_pos_5
	 }
#declare mol_0_bond10 = object {
	  bond_1
	  scale <1.02425,1.0000,1.0000>
	  rotate <0.0000,0.0000,-12.5669>
	  rotate <0.0000,107.162,0.0000>
	  translate mol_0_pos_6
	 }
#declare mol_0_bond11 = object {
	  bond_1
	  scale <1.02397,1.0000,1.0000>
	  rotate <0.0000,0.0000,-4.80493>
	  rotate <0.0000,2.63491,0.0000>
	  translate mol_0_pos_6
	 }
#end //(BAS-Bonds)

#if (CST)
#declare mol_0_bond0 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.761447,1.0000,1.0000>
	    rotate <0.0000,0.0000,-1.00052>
	    rotate <0.0000,-0.516857,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.761447,1.0000,1.0000>
	    rotate <0.0000,0.0000,178.999>
	    rotate <0.0000,-0.516857,0.0000>
	    translate mol_0_pos_2
	   }
	  }
	 }

#declare mol_0_bond1 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.769595,1.0000,1.0000>
	    rotate <0.0000,0.0000,-63.2056>
	    rotate <0.0000,40.0177,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_C2}
	    scale <0.769595,1.0000,1.0000>
	    rotate <0.0000,0.0000,116.794>
	    rotate <0.0000,40.0177,0.0000>
	    translate mol_0_pos_3
	   }
	  }
	 }

#declare mol_0_bond2 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_C2}
	    scale <0.612107,1.0000,1.0000>
	    rotate <0.0000,0.0000,-8.70205>
	    rotate <0.0000,56.6834,0.0000>
	    translate mol_0_pos_3
	   }
	   object {
	    bond_2
	    pigment{color Color_O2}
	    scale <0.612107,1.0000,1.0000>
	    rotate <0.0000,0.0000,171.298>
	    rotate <0.0000,56.6834,0.0000>
	    translate mol_0_pos_4
	   }
	  }
	 }

#declare mol_0_bond3 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C2}
	    scale <0.676621,1.0000,1.0000>
	    rotate <0.0000,0.0000,-48.052>
	    rotate <0.0000,-109.728,0.0000>
	    translate mol_0_pos_3
	   }
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.676621,1.0000,1.0000>
	    rotate <0.0000,0.0000,131.948>
	    rotate <0.0000,-109.728,0.0000>
	    translate mol_0_pos_5
	   }
	  }
	 }

#declare mol_0_bond4 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.738881,1.0000,1.0000>
	    rotate <0.0000,0.0000,45.9211>
	    rotate <0.0000,60.5012,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_N3}
	    scale <0.738881,1.0000,1.0000>
	    rotate <0.0000,0.0000,225.921>
	    rotate <0.0000,60.5012,0.0000>
	    translate mol_0_pos_6
	   }
	  }
	 }

#declare mol_0_bond5 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.547544,1.0000,1.0000>
	    rotate <0.0000,0.0000,-41.0442>
	    rotate <0.0000,-120.044,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.547544,1.0000,1.0000>
	    rotate <0.0000,0.0000,138.956>
	    rotate <0.0000,-120.044,0.0000>
	    translate mol_0_pos_7
	   }
	  }
	 }

#declare mol_0_bond6 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.548021,1.0000,1.0000>
	    rotate <0.0000,0.0000,-13.6817>
	    rotate <0.0000,111.88,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.548021,1.0000,1.0000>
	    rotate <0.0000,0.0000,166.318>
	    rotate <0.0000,111.88,0.0000>
	    translate mol_0_pos_8
	   }
	  }
	 }

#declare mol_0_bond7 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.547807,1.0000,1.0000>
	    rotate <0.0000,0.0000,64.6957>
	    rotate <0.0000,-144.289,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.547807,1.0000,1.0000>
	    rotate <0.0000,0.0000,244.696>
	    rotate <0.0000,-144.289,0.0000>
	    translate mol_0_pos_9
	   }
	  }
	 }

#declare mol_0_bond8 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.547624,1.0000,1.0000>
	    rotate <0.0000,0.0000,10.5358>
	    rotate <0.0000,-69.3152,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.547624,1.0000,1.0000>
	    rotate <0.0000,0.0000,190.536>
	    rotate <0.0000,-69.3152,0.0000>
	    translate mol_0_pos_10
	   }
	  }
	 }

#declare mol_0_bond9 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.487856,1.0000,1.0000>
	    rotate <0.0000,0.0000,16.5717>
	    rotate <0.0000,-122.589,0.0000>
	    translate mol_0_pos_5
	   }
	   object {
	    bond_1
	    pigment{color Color_HO}
	    scale <0.487856,1.0000,1.0000>
	    rotate <0.0000,0.0000,196.572>
	    rotate <0.0000,-122.589,0.0000>
	    translate mol_0_pos_11
	   }
	  }
	 }

#declare mol_0_bond10 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_N3}
	    scale <0.512126,1.0000,1.0000>
	    rotate <0.0000,0.0000,-12.5669>
	    rotate <0.0000,107.162,0.0000>
	    translate mol_0_pos_6
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.512126,1.0000,1.0000>
	    rotate <0.0000,0.0000,167.433>
	    rotate <0.0000,107.162,0.0000>
	    translate mol_0_pos_12
	   }
	  }
	 }

#declare mol_0_bond11 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_N3}
	    scale <0.511985,1.0000,1.0000>
	    rotate <0.0000,0.0000,-4.80493>
	    rotate <0.0000,2.63491,0.0000>
	    translate mol_0_pos_6
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.511985,1.0000,1.0000>
	    rotate <0.0000,0.0000,175.195>
	    rotate <0.0000,2.63491,0.0000>
	    translate mol_0_pos_13
	   }
	  }
	 }

#end // (CST-Bonds)


//All atoms of molecule mol_0
#ifdef (TRANS)
#declare mol_0_atoms = merge {
#else
#declare mol_0_atoms = union {
#end //(End of TRANS)
	  object{mol_0_atom1}
	  object{mol_0_atom2}
	  object{mol_0_atom3}
	  object{mol_0_atom4}
	  object{mol_0_atom5}
	  object{mol_0_atom6}
	  object{mol_0_atom7}
	  object{mol_0_atom8}
	  object{mol_0_atom9}
	  object{mol_0_atom10}
	  object{mol_0_atom11}
	  object{mol_0_atom12}
	  object{mol_0_atom13}
	 }

//Bonds only needed for ball and sticks or capped sticks models
#if (BAS | CST)
#declare mol_0_bonds = union {
	  object{mol_0_bond0}
	  object{mol_0_bond1}
	  object{mol_0_bond2}
	  object{mol_0_bond3}
	  object{mol_0_bond4}
	  object{mol_0_bond5}
	  object{mol_0_bond6}
	  object{mol_0_bond7}
	  object{mol_0_bond8}
	  object{mol_0_bond9}
	  object{mol_0_bond10}
	  object{mol_0_bond11}
	 }
#end


//Definition of molecule mol_0
#if (SPF)
#declare mol_0 = object{
	  mol_0_atoms
#else
#declare mol_0 = union {
	  object{mol_0_atoms}
#if (BAS | CST)//(Not really needed at moment!)
#if (TRANS)
	  difference {
	   object{mol_0_bonds}
	   object{mol_0_atoms}
	  }
#else
	  object{mol_0_bonds}
#end //(End of TRANS)
#end //(End of (BAS|CST))
#end //(End of SPF)
//	  bounded_by {
//	   box {
//	    <-3,-5.49741,-4.92271>
//	    <7.01605,3.94459,4.1205>
	 }

//Center of molecule mol_0 (bounding box)
#declare mol_0_center = <-2.00802,0.776413,0.401106>;

// mol_0
